# Setup
title:        The DevOps corner
tagline:      Thoughts & Ideas around the DevOps philosophy
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Bastien Semene
  url:        http://bastien.semene.fr

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
